# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20161115_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(blank=True, choices=[(b'OFA', b'OfflineAds'), (b'ONA', b'OnlineAds'), (b'IR', b'InternalReferral'), (b'ER', b'ExternalReferral'), (b'P', b'Partner'), (b'S', b'Sales'), (b'TS', b'TradeShow'), (b'SR', b'Seminar')], db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[(b'O', b'Open'), (b'C', b'Closed'), (b'CV', b'Converted')], db_index=True, default=b'O', max_length=2),
        ),
    ]
