# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_auto_20161115_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[(b'O', b'Open'), (b'P', b'Progress'), (b'CW', b'ClosedWon'), (b'CL', b'ClosedLost')], db_index=True, default=b'O', max_length=2),
        ),
    ]
