# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[(b'L', b'Lead'), (b'T', b'Task'), (b'E', b'Event'), (b'DL', b'Deal')], max_length=2)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[(b'Q', b'Queue'), (b'P', b'Progress'), (b'D', b'Done'), (b'E', b'Error')], default=b'Q', max_length=2)),
                ('url', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='employees.Employee')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='entities.Entity')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_reports', to='employees.Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
