# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='start_time',
            new_name='start_date',
        ),
    ]
