# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20161202_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='employee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='report',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
