# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20161202_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='employees.Employee'),
        ),
    ]
