# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20161115_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[(b'H', b'High'), (b'M', b'Medium'), (b'L', b'Low')], db_index=True, default=b'M', max_length=2),
        ),
    ]
