# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20161127_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
