"""
Django settings for zapdos_api project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from datetime import timedelta

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'bt!bl91a)v8244^-6w2x$m2e!*gxsw#85i2nzgl42mz(l_rf*8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'rest_framework_docs',
    'corsheaders',
    'bases',
    'accounts',
    'entities',
    'employees',
    'leads',
    'companies',
    'customers',
    'deals',
    'tasks',
    'notes',
    'rest_framework',
    'timelines',
    'events',
    'algolias',
    'devices',
    'reports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zapdos_api.urls'

AUTH_USER_MODEL = 'accounts.Account'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zapdos_api.wsgi.application'



# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'zahaya',
        'USER': 'angkywilliam',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
    ),

    'DEFAULT_PARSER_CLASSES': (
        'djangorestframework_camel_case.parser.CamelCaseJSONParser',
    ),

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',

    'PAGE_SIZE': 20,

    'DATETIME_FORMAT': "%Y-%m-%dT%H:%M:%S.%fZ",
}

TOKEN_TIME = 30*24*3600

JWT_AUTH = {
    'JWT_EXPIRATION_DELTA': timedelta(seconds=TOKEN_TIME),
    'JWT_PAYLOAD_HANDLER': 'employees.tokens.jwt_custom_payload_handler',
}

TIMELINE_SIZE = 50

ACCOUNT_ACTIVATION_DAYS = 7


EMAIL_ADDRESS = 'hello@zahaya.com'
EMAIL_PASSWORD = 'zahayabersama'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = EMAIL_ADDRESS
EMAIL_HOST_PASSWORD = EMAIL_PASSWORD
EMAIL_PORT = 587
EMAIL_USE_TLS = True


ALGOLIA = {
    'APPLICATION_ID': '1UO158NSFF',
    'API_KEY': '3e590e37b7ec2582d3bf8a9bf2754b77',
    'INDEX_SUFFIX': 'local',
    'SEARCH_API_KEY': '042ad674925d9fc4195b3f2254f02892'
}

CLOUDINARY = {
    'ENDPOINT': 'api.cloudinary.com/v1_1/dfvk9ca4v/image/upload',
    'PRESET': 'khgrmml4'
}

CORS_ORIGIN_ALLOW_ALL = True

BROKER_URL = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

S3_ACCESS_KEY = 'AKIAIBLYLOBMVFWPVDEA'
S3_SECRET_KEY = '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'
S3_ENDPOINT = 's3-ap-southeast-1.amazonaws.com'
S3_BUCKET = 'local-zahaya-export'