# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('employee_num', models.IntegerField(blank=True, default=0)),
                ('annual_revenue', models.BigIntegerField(blank=True, default=0)),
                ('company_website', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('prof_pic', models.TextField(blank=True)),
                ('street', models.TextField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('pos_code', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(blank=True, default='IDR', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expired', models.DateTimeField()),
                ('max_user', models.IntegerField(default=99)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
